### ISSUE TITLE
[BUG] Models not overridden when you re-run Build Models

### ISSUE THREAD

**Issue by Prn-Ice** [hiranthaR/Json-to-Dart-Model#59]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Say I have the following in my `models.jsonc`

```json
{
		"__className": "db_options",
		"__path": "/lib/app/core/data/models/db_options",
		"d@biometricsEnabled": false,
		"d@fontScalingEnabled": true,
		"d@liteModeEnabled": false,
		"d@showBiometricsDialog": true,
		"d@token": ""
	},
```

If I added a new field to the above json and rerun build models, I get told that `db_options.dart` already exists. 
I then have to delete the previously generated file and rerun the command for it to build successfully.

### Expected Behavior

The previously generated file should be overriden.

### Version

```markdown
3.3.6
```

### Relevant JSON syntax

```shell
{
		"__className": "db_options",
		"__path": "/lib/app/core/data/models/db_options",
		"d@biometricsEnabled": false,
		"d@fontScalingEnabled": true,
		"d@liteModeEnabled": false,
		"d@showBiometricsDialog": true,
		"d@token": ""
	},
```

**Comment by iamarnas** [comment]
@Prn-Ice Hi :wave:

 Here is not a bug, the generator work with duplicates files in this way and guarantees to not override old files. Because this generator split the big nested JSON objects into separate files and is a big risk to override some important files by mistake. For example, hand modified or well documented. And it's documented that if you want to update files you need to delete old ones. And I think it does not happen so often, that's safer to delete it manually.

**Comment by Prn-Ice** [comment]
I see, thanks.
